auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create_listing, name="create_listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("listings/<int:listing_id>", views.listing, name="listing"),
    path("listings/<int:listing_id>/add-to-watchlist", views.add_to_watchlist, name="add_to_watchlist"),
    path("listings/<int:listing_id>/remove-from-watchlist", views.remove_from_watchlist, name="remove_from_watchlist"),
    path("listings/<int:listing_id>/place-bid", views.place_bid, name="place_bid"),
    path("listings/<int:listing_id>/close-listing", views.close_listing, name="close_listing"),
    path("listings/<int:listing_id>/comment", views.comment, name="comment"),
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.category, name="category"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings


class User(AbstractUser):
    pass



class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Listing(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="listings") 
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="created_listings")
    title = models.CharField(max_length=255)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    current_bid = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    image_data = models.URLField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title} : listed by {self.seller.username} under the {self.category} category"


class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listings = models.ManyToManyField(Listing, blank=True, related_name="listings")

    def __str__(self):
        return self.user.username + "'s Watchlist"


class Bid(models.Model):
    bidder = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    bid_amount = models.DecimalField(max_digits=12, decimal_places=2)
    bid_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.listing.title} : {self.bidder.username} bidded {self.bid_amount} ({self.bid_time})"
    

class Comment(models.Model):
    commenter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    comment_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.commenter.username} on {self.listing.title} : {self.comment[:20]}..."

auctions/forms.py
from django import forms
from django.forms import ModelForm

from .models import Listing

class CreateListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ['category', 'title', 'description', 'starting_bid', 'image_data']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select fs-4 p-3', 'id': 'category', "required": "required",}),
            'title': forms.TextInput(attrs={'class': 'form-control fs-4 p-3', 'id': 'title', 'placeholder': '', "required": "required",}),
            'description': forms.Textarea(attrs={'class': 'form-control fs-4 p-3', 'id': 'description', "required": "required",}),
            'starting_bid': forms.NumberInput(attrs={'class': 'form-control fs-4 p-3', 'id': 'starting_bid', "required": "required",}),
            'image_data': forms.URLInput(attrs={'class': 'form-control fs-4 p-3', 'id': 'image_data'}),
        }
        
        
    

auctions/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from .models import User, Category, Listing, Watchlist, Bid, Comment
from .forms import CreateListingForm

from decimal import *


def index(request):
    return render(request, "auctions/index.html", {
        "active_listings": Listing.objects.filter(is_active=True)
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return render(request, "auctions/login.html", {
        "message": "Logged out."
    })


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def categories(request):
    return render(request, "auctions/categories.html", {
        "categories": Category.objects.all()
    })


def category(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        raise Http404("Category not found.")
    return render(request, "auctions/category.html", {
        "category": category,
        "active_listings": Listing.objects.filter(is_active=True, category=category)
    })


def listing(request, listing_id):
    if request.user.is_authenticated:
        try:
            listing = Listing.objects.get(id=listing_id)

            if listing.bids.all().first() == None:
                listing.current_bid = listing.starting_bid
            else: 
                listing.current_bid = listing.bids.all().last().bid_amount
            
            listing.save()
        except Listing.DoesNotExist:
            return HttpResponseBadRequest("Listing not found.")


        return render(request, "auctions/listing.html", {
            "listing": listing,
            "in_watchlist": Watchlist.objects.filter(user=request.user, listings=listing).exists(),
            "all_bids": listing.bids.all().order_by('-bid_time'),
            "highest_bid": get_highest_bid(listing_id),
            "all_comments": listing.comments.all().order_by('-comment_time'),
        })
    return HttpResponseRedirect(reverse('auctions:login'))


# @login_required
def create_listing(request):
    if request.method == "POST":
        form = CreateListingForm(request.POST)

        if form.is_valid():
            listing = form.save(commit=False)
            listing.seller = request.user
            listing.current_bid = listing.starting_bid
            form.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        
    else:
        return render(request, "auctions/create_listing.html", {
            "form" : CreateListingForm()
        })


# @login_required
def add_to_watchlist(request, listing_id):
    if request.method == "POST":
        listing = get_object_or_404(Listing, id=listing_id)
        watchlist, just_created = Watchlist.objects.get_or_create(user=request.user)
        watchlist.listings.add(listing)

    return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))


# @login_required
def remove_from_watchlist(request, listing_id):
    if request.method == "POST":
        listing = get_object_or_404(Listing, id=listing_id)
        watchlist = Watchlist.objects.get(user=request.user)
        watchlist.listings.remove(listing)

        return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))


# @login_required
def watchlist(request):
    try:
        watchlist = Watchlist.objects.get(user=request.user)
        listings = watchlist.listings.all()
    except Watchlist.DoesNotExist:
        return HttpResponseBadRequest("Nothing here in watchlist.")
    return render(request, "auctions/watchlist.html", {
        "listings": listings
    })


# @login_required
def place_bid(request, listing_id):
    if request.method == "POST":
        listing = get_object_or_404(Listing, id=listing_id)
        # get bid that is in request
        bid_placed = request.POST["bid"]
        # get all bids of the list
        all_bids = [bid.bid_amount for bid in listing.bids.all()]

        # IF the bid_placed is greater than any other bids, then bid successful
        # ELSE, return an error message
        if all_bids == [] or all(Decimal(bid_placed) > bid for bid in all_bids):
            listing.current_bid = bid_placed
            listing.save()
            Bid.objects.create(bidder=request.user, listing=listing, bid_amount=bid_placed)
        else:
            messages.error(request, "Your bid is too low. Bid higher.")
    
    return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))


def get_highest_bid(listing_id):
    try:
        listing = get_object_or_404(Listing, id=listing_id)
        highest_bid = Bid.objects.filter(listing=listing).order_by('-bid_amount').first()
        return highest_bid
    except Bid.DoesNotExist:
        return None
    

# @login_required
def close_listing(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)
    listing.is_active = False
    listing.save()
    return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))


@login_required
def comment(request, listing_id):
    if request.method == "POST":
        # get list
        listing = get_object_or_404(Listing, id=listing_id)

        # get comment
        comment = request.POST["comment"]

        # add new comment to the list
        Comment.objects.create(commenter=request.user, listing=listing, comment=comment)

    return HttpResponseRedirect(reverse("auctions:listing", args=(listing_id,)))

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}


<h1 class="mt-5 fw-light pt-sm-5">Categories</h1>

<div class="mt-5">
  <div class="row g-5">
    {% for category in categories %}
    <div class="col-sm-6 col-md-4 col-lg-3">
      <a class="text-reset text-decoration-none" href="{% url 'auctions:category' category.id %}">
        <div class="list">
          <div class="card-body category-box">
            <p class="text-nowrap fs-3 m-0 px-4 py-3">{{ category }} </p>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<h1 class="my-5 fw-light pt-sm-5">Create a listing</h1>

<form action="{% url 'auctions:create_listing' %}" method="post">
  {% csrf_token %}

  <!-- TITLE and CATEGORY -->
  <div class="row">
    <div class="col-md-6">
      <div class="mb-5">
        <label for="title" class="form-label fs-4 mb-2">Title</label>
        <div class="input-group">
          {{ form.title }}
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="mb-5">
        <label for="category" class="form-label fs-4 mb-2">Select category</label>
        <div class="input-group fs-4">
          {{ form.category }}
        </div>
      </div>
    </div>
  </div>

  <!-- STARTING BID and UPLOAD IMAGE -->
  <div class="row">
    <div class="col-md-6">
      <div class="mb-5">
        <label for="starting_bid" class="form-label fs-4 mb-2">Starting bid</label>
        <div class="input-group">
          <span class="input-group-text fs-5 px-4">$</span>
          {{ form.starting_bid }}
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="mb-5">
        <label for="image_data" class="form-label fs-4 mb-2">Upload Image</label>
        <div class="input-group">
          <span class="input-group-text fs-5 px-4">Image URL</span>
          {{ form.image_data }}
        </div>
      </div>
    </div>
  </div>


  <div class="mb-5">
    <label for="description" class="form-label fs-4 mb-2">Description</label>
    <div class="input-group">
      {{ form.description }}
    </div>
  </div>


  <input class="create-btn fs-4 float-end mb-5 px-4" type="submit" value="Save and Exit">
</form>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">

    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- local css file  -->
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">

    <!-- fontawesome icons -->
    <script src="https://kit.fontawesome.com/363a78aff8.js" crossorigin="anonymous"></script>

    <title>{% block title %}Auctions{% endblock %}</title>
</head>

<body>
    {% block hero %}
    <div class="container-xl px-5 py-4">
        <header class="navbar navbar-expand-sm pt-4 pt-md-0 pb-5">
            <div class="w-100 d-flex d-sm-none justify-content-between">
                <div class="d-sm-none align-self-center px-1" data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="fa-solid fa-bars fs-2"></span>
                </div>

                <div class="">
                    {% if user.is_authenticated %}
                    <div></div>
                    {% else %}
                    <a class="text-decoration-none text-reset fs-4" href="{% url 'auctions:login' %}">
                        <button type="button" class="logout-btn">
                            <i class="fa-solid fa-arrow-right-from-bracket me-2"></i>
                            Login
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>

            <!-- Site Logo -->
            <h1 class="navbar-brand mb-0 ms-4 ms-sm-0 py-3 d-none d-sm-block">
                <a href="{% url 'auctions:index' %}" aria-current="page"
                    class="text-reset text-decoration-none display-6 fw-normal dark">BidMasters</a>
            </h1>

            <!-- NAVBAR -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="navbar-nav w-100">
                    <!-- Categories -->
                    <div class="nav-item align-self-center ms-sm-5 me-sm-4">
                        <a class="text-decoration-none text-reset fs-4 dark" href="{% url 'auctions:categories' %}">
                            Categories
                        </a>
                    </div>
                    {% if user.is_authenticated %}
                    <div class="w-100 d-none d-sm-flex justify-content-sm-between">
                        <!-- Watchlist -->
                        <div class="nav-item align-self-center">
                            <a class="text-decoration-none text-reset fs-4 dark"
                                href="{% url 'auctions:watchlist' %}">My
                                Watchlist</a>
                        </div>
                        <!-- Create Listing and Logout -->
                        <div class="d-inline-flex">
                            <a class="text-decoration-none text-reset align-self-center fs-4 dark"
                                href="{% url 'auctions:create_listing' %}">
                                <button type="button" class="nav-item create-btn">
                                    <i class="fa-solid fa-plus"></i>
                                </button>
                            </a>
                            <a class="text-decoration-none text-reset fs-4" href="{% url 'auctions:logout' %}">
                                <button type="button" class="nav-item ms-3 logout-btn">
                                    <i class="fa-solid fa-arrow-right-from-bracket me-2"></i>
                                    Logout
                                </button>
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="nav-item w-100">
                        <a class="text-decoration-none text-reset fs-4" href="{% url 'auctions:login' %}">
                            <button type="button" class="w-auto logout-btn float-end">
                                <i class="fa-solid fa-arrow-right-from-bracket me-2"></i>
                                Login
                            </button>
                        </a>
                    </div>
                    {% endif %}
                </div>
            </div>

            <!-- Sidebar for Mobile Menu -->
            <div class="offcanvas offcanvas-start d-sm-none p-3 sidebar" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h1 class="offcanvas-title display-5 fw-normal" id="offcanvasNavbarLabel dark">BidMasters</h1>
                    <span class="fa-solid fa-x fs-3" data-bs-dismiss="offcanvas" aria-label="Close"></span>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav h-100 justify-content-between">
                        <div class="">
                            <li class="nav-item my-5">
                                <a class="text-decoration-none text-reset fs-2 dark" aria-current="page"
                                    href="{% url 'auctions:index' %}">Home</a>
                            </li>
                            <li class="nav-item mb-5">
                                <a class="text-decoration-none text-reset fs-2 dark"
                                    href="{% url 'auctions:categories' %}">Categories</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item mb-5">
                                <a class="text-decoration-none text-reset fs-2 dark"
                                    href="{% url 'auctions:watchlist' %}">My
                                    Watchlist</a>
                            </li>
                            <li class="nav-item mb-5">
                                <a class="text-decoration-none text-reset fs-2 dark"
                                    href="{% url 'auctions:create_listing' %}">Create Listing</a>
                            </li>
                        </div>
                        <li class="nav-item mb-5">
                            <a class="text-decoration-none text-reset fs-2 dark" href="{% url 'auctions:logout' %}">
                                <i class="fa-solid fa-arrow-right-from-bracket me-2"></i> Logout</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </header>

        <!-- signed in as -->
        <!-- <div>
            {% if user.is_authenticated %}
            Hello, <strong>{{ user.username }}</strong>!
            {% else %}
            Not signed in.
            {% endif %}
        </div> -->
        {% block body %}
        {% endblock %}
    </div>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

    <script src="{% static 'auctions/main.js' %}"></script>
</body>

</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% load static %}
{% load customize %}

{% block body %}



<div class="row mt-5 g-0">
  <!-- IMAGE -->
  <div class="col-md-6 col-lg-7 mt-3 mt-md-5">
    <div class="px-0 pe-lg-2">
      {% if listing.image_data %}
      <img class="w-100 h-100 object-fit-cover listing-img" src="{{ listing.image_data }}"
        alt="{{ listing.description }}">
      {% else %}
      <img class="w-100 h-100 object-fit-cover listing-img" src="{% static 'auctions/images/no_image.png' %}"
        alt="Default image">
      {% endif %}
    </div>
  </div>

  <!-- BRIEF BACKGROUND AND PLACE BID -->
  <div class="col-md-6 col-lg-5 mt-3 mt-md-5">
    <div class="px-0 ms-md-5 ps-lg-5">
      <!-- CATEGORY -->
      <span class="fs-4">{{ listing.category }}</span>
      <!-- TITLE -->
      <h1 class="display-6 fw-semibold mt-2 mb-4 text-wrap">{{ listing.title }}</h1>
      <!-- <span>by {{ listing.seller }}</s  -->
      <!-- ADD TO WATCHLIST or REMOVE FROM WATCHLIST or CLOSE LISTING -->
      <div class="mb-5">
        {% if user != listing.seller %}

        <!-- ADD or REMOVE for user who is not the seller  -->
        {% if not in_watchlist %}
        <form action="{% url 'auctions:add_to_watchlist' listing.id %}" method="POST">
          {% csrf_token %}
          <input class="fs-5 fw-medium update-listing-btn" type="submit" value="Add to Watchlist">
        </form>
        {% else %}
        <form action="{% url 'auctions:remove_from_watchlist' listing.id %}" method="POST">
          {% csrf_token %}
          <input class="fs-5 fw-medium update-listing-btn" type="submit" value="Remove from Watchlist">
        </form>
        {% endif %}

        {% else %}

        <!-- CLOSE the bidding -->
        {% if listing.is_active %}
        <a class="text-reset text-decoration-none" href="{% url 'auctions:close_listing' listing.id %}">
          <button class="fs-5 fw-medium update-listing-btn border">Close Listing</button>
        </a>
        </button>
        {% endif %}

        {% endif %}
      </div>

      <!-- SHOW CURRENT BID and WINNER -->
      <div class="">
        {% if highest_bid == None %}
        <p class="fs-4 mt-5 pt-5 mb-0">Starting bid</p>
        <span class="fs-1 fw-medium">$ {{ listing.starting_bid }}</span>
        {% else %}
        {% if listing.is_active %}
        {% if highest_bid.bidder == user %}
        <h3>You are the highest bidder!</h3>
        {% else %}
        <p class="fs-4 mb-0">
          Highest bid by
          <span class="fw-medium beige-dark">{{ highest_bid.bidder}}</span>
        </p>
        {% endif %}
        {% else %}
        {% if highest_bid.bidder == user %}
        <h3>You won the auction!</h3>
        {% endif %}
        {% if listing.seller == user %}
        <h3>You closed this listing.</h3>
        <p class="fs-4 mt-5 my-0 py-0">
          <span class="fw-medium beige-dark">{{ highest_bid.bidder}}</span>
          won this auction!
        </p>
        {% endif %}
        {% endif %}
        <span class="fs-1 fw-medium">$ {{ highest_bid.bid_amount }}</span>
        {% endif %}
      </div>

      <!-- PLACE BID -->
      {% if not listing.seller == user %}
      <div class="d-none d-md-block">
        {% if listing.is_active %}
        <div class="error-bid-div">
          {% for message in messages %}
          <div
            class="alert alert-dismissible fade show fs-5 fw-medium w-100 px-3 py-0 m-0 d-flex justify-content-between error-bid-box"
            role="alert">
            <span class="align-self-center">
              {{ message }}
            </span>
            <button type="button" class="close border-0 bg-transparent" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true" class="dark fs-3">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>

        <form action="{% url 'auctions:place_bid' listing.id %}" method="POST" id="bidForm">
          {% csrf_token %}
          <div class="w-100">
            <input class="w-100 p-4 fs-4 mb-3 place-bid-input" type="number" inputmode="numeric" name="bid" id="bid"
              min="{{ listing.starting_bid }}" max="999 999 999 999" step="0.10"
              placeholder="$ {{ listing.current_bid }} or more" aria-describedby="place-bid" required>
            <button class="w-100 p-3 fs-4 place-bid-btn text-uppercase" type="submit">Place bid</button>
          </div>
        </form>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

<div class="row mt-sm-3 mt-md-5 g-0">
  <!-- PLACE BID and BID HISTORY -->
  <div class="col-md-6 col-lg-5 order-md-1">
    <div class="px-0 ms-md-5 ps-lg-5 mb-5 list">
      {% if not listing.seller == user %}
      <div class="d-block d-md-none mb-5 pb-5">
        {% if listing.is_active %}
        <div class="error-bid-div">
          {% for message in messages %}
          <div
            class="alert alert-dismissible fade show fs-5 fw-medium w-100 px-3 py-0 m-0 d-flex justify-content-between error-bid-box"
            role="alert">
            <span class="align-self-center">
              {{ message }}
            </span>
            <button type="button" class="close border-0 bg-transparent" data-bs-dismiss="alert" aria-label="Close">
              <span aria-hidden="true" class="dark fs-3">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>

        <form action="{% url 'auctions:place_bid' listing.id %}" method="POST" id="bidForm">
          {% csrf_token %}
          <div class="w-100">
            <input class="w-100 p-4 fs-4 mb-3 place-bid-input" type="number" inputmode="numeric" name="bid" id="bid"
              min="{{ listing.starting_bid }}" max="999 999 999 999" step="0.10"
              placeholder="$ {{ listing.current_bid }} or more" aria-describedby="place-bid" required>
            <button class="w-100 p-3 fs-4 place-bid-btn text-uppercase" type="submit">Place bid</button>
          </div>
        </form>
        {% endif %}
      </div>
      {% endif %}

      <h2>Bid History</h2>
      <ul class="list-group mt-5 overflow-auto bid-history">
        {% for bid in all_bids %}
        <li class="list-group-item border-0 mb-4 px-0">
          <div class="mb-2 d-flex w-100 justify-content-between">
            <div class="">
              <p class="fs-4 mb-1">Bid placed by {{ bid.bidder }} </p>
              <span class="fs-5 text-body-secondary">{{ bid.bid_time|time_ago }} ago</span>
            </div>
            <p class="fs-3 fw-medium mb-1 align-self-center">$ {{ bid.bid_amount }}</p>
          </div>
        </li>
        {% empty %}
        <li class="list-group-item border-0 mb-4 px-0">
          <p class="fs-4 mb-1">No bids yet</p>
        </li>
        {% endfor %}

      </ul>
    </div>
  </div>

  <!-- DESCRIPTION and COMMENTS -->
  <div class="col-md-6 col-lg-7">
    <div class="px-0 pe-lg-2">
      <!-- DESCRIPTION -->
      <div class="mx-0">
        <h2 class="mb-4 px-0">Description</h2>
        <p class="mb-0 fw-light fs-4 px-0 mb-5">{{listing.description}}</p>
      </div>

      <!-- COMMENT -->
      <div class="pt-5 mt-5 mx-0">
        <h2 class="mb-4 px-0">Comments</h2>
        <!-- ADD COMMENT -->
        <form action="{% url 'auctions:comment' listing.id %}" method="POST" class="px-0 pb-5">
          {% csrf_token %}
          <textarea class="w-100 fs-4 py-1 comment-box" name="comment" id="comment" placeholder="Add a comment"
            aria-label="comment" rows="1" required></textarea>
          <button type="submit" class="fs-4 float-end create-btn">Post comment</button>
        </form>

        <!-- COMMENTS -->
        <ul class="list-group mt-5 overflow-auto comment-history">
          {% for comment in all_comments %}
          <li class="list-group-item border-0 mb-4 px-0">
            <div class="mb-2 d-flex w-100 justify-content-between">
              <h4 class="mb-1"> {{ comment.commenter }} </h4>
              <small class="fs-5 text-body-secondary">{{ comment.comment_time|time_ago }} ago</small>
            </div>
            <p class="fs-4 fw-light mb-1">{{ comment.comment }}</p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>




{% endblock %}